version: '3'

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    # ports:
    #   - 27017:27017 I commented this to do not expose the database using table plus or another client, only using mongo express 
    restart: always  
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=mongoadmin these forms are the same
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth'] # when the image is release, execute --auth

  mongo-express:  
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
    ports:
      - 8080:8081
    restart: always  


volumes:
  poke-vol:
    external: false     