version: '3'

services:
  db:
    container_name: ${MONGO_DB_NAME_AND_NETWORK_SERVER_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    # ports:
    #   - 27017:27017 I commented this to do not expose the database using table plus or another client, only using mongo express 
    restart: always  
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=mongoadmin these forms are the same
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth'] # when the image is release, execute --auth

  mongo-express:  
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME_AND_NETWORK_SERVER_NAME}
    ports:
      - 8080:8081
    restart: always  

  poke-app:
    depends_on:
      - db
      - mongo-express
    image: klerith/pokemon-nest-app:1.0.0 # This came from: https://hub.docker.com/r/klerith/pokemon-nest-app/tags
    ports:
      - 3000:3000
    environment:
      MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME_AND_NETWORK_SERVER_NAME}:27017
      DB_NAME: ${MONGO_DB_NAME_AND_NETWORK_SERVER_NAME}
    restart: always # this is in case the container stops     



volumes:
  poke-vol:
    external: false     